INSERT INTO ESTADO VALUES(1, 'Miranda',232);
INSERT INTO ESTADO VALUES(2, 'Zulia',232);
INSERT INTO ESTADO VALUES(3, 'Carabobo',232);
INSERT INTO ESTADO VALUES(4, 'Lara',232);
INSERT INTO ESTADO VALUES(5, 'Bolívar',232);
INSERT INTO ESTADO VALUES(6, 'Aragua',232);
INSERT INTO ESTADO VALUES(7, 'Vargas',232);
INSERT INTO ESTADO VALUES(8, 'Táchira',232);
INSERT INTO ESTADO VALUES(9, 'Anzoátegui',232);
INSERT INTO ESTADO VALUES(10, 'Monagas',232);
INSERT INTO ESTADO VALUES(11, 'Barinas',232);
INSERT INTO ESTADO VALUES(12, 'Sucre',232);
INSERT INTO ESTADO VALUES(13, 'Falcón',232);
INSERT INTO ESTADO VALUES(14, 'Mérida',232);
INSERT INTO ESTADO VALUES(15, 'Trujillo',232);
INSERT INTO ESTADO VALUES(16, 'Portuguesa',232);
INSERT INTO ESTADO VALUES(17, 'Apure',232);
INSERT INTO ESTADO VALUES(18, 'Guárico',232);
INSERT INTO ESTADO VALUES(19, 'Yaracuy',232);
INSERT INTO ESTADO VALUES(20, 'Cojedes',232);
INSERT INTO ESTADO VALUES(21, 'Amazonas',232);
INSERT INTO ESTADO VALUES(22, 'Nueva Esparta',232);
INSERT INTO ESTADO VALUES(23, 'Distrito Capital',232);
INSERT INTO ESTADO VALUES(24, 'Cojedes',232);
INSERT INTO ESTADO VALUES(25, 'Delta Amacuro',232);












